import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>tRPC Demo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center h-screen p-4">
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
          E2E Typescript Demo
        </h1>

        <div className="grid gap-3 pt-3 mt-3 text-center md:grid-cols-2 lg:w-2/3">
          <LinkCard
            title="REST Example"
            href="/rest"
            description="Example of the posts page using the common REST technology"
          />
          <LinkCard
            title="tRPC Example"
            href="/trpc"
            description="Example of the posts page using end-to-end typing with tRPC"
          />
        </div>
      </main>
    </>
  );
};

type LinkCardProps = {
  title: string;
  href: string;
  description: string;
};

function LinkCard(props: LinkCardProps) {
  const { title, href, description } = props;
  return (
    <Link href={href}>
      <section className="flex flex-col justify-center p-6 duration-200 border-2 border-gray-500 rounded shadow-xl motion-safe:hover:scale-105 cursor-pointer">
        <h2 className="text-xl text-gray-700">{title}</h2>
        <p className="text-md text-gray-500"> {description}</p>
      </section>
    </Link>
  );
}

export default Home;
